### ISSUE TITLE
Add new paper

### ISSUE THREAD

**Issue by RishabhMaheshwary** [thunlp/TAADpapers#17]
Request to add a new paper:
**Generating Natural Language Attacks in a Hard Label Black Box Setting**, accepted in AAAI 2021 main conference.
Paper: Link to [paper.](https://arxiv.org/abs/2012.14956)
Code: Link to [code](https://github.com/RishabhMaheshwary/hard-label-attack).

Brief Outline:
The paper proposes a novel decision based attack strategy that utilizes population-based optimization algorithm to generate adversarial examples by observing only the topmost predicted label.

**Comment by RishabhMaheshwary** [comment]
The paper is in the [accepted paper list](https://aaai.org/Conferences/AAAI-21/wp-content/uploads/2020/12/AAAI-21_Accepted-Paper-List.Main_.Technical.Track_.pdf) of AAAI 2021.

**Comment by yangalan123** [comment]
Big thanks for the paper recommendation! Sorry, we are busy with the ACL deadline. Will check and merge later.

**Comment by yangalan123** [comment]
Your paper has been added. Thanks for the recommendation and if you have any problem, please re-open the issue again!
