### ISSUE TITLE
Add two new papers

### ISSUE THREAD

**Issue by xiaosen-wang** [thunlp/TAADpapers#22]
Hello, please add our papers for adversarial defense against synonym substitution based attacks:

Adversarial Training with Fast Gradient Projection Method against Synonym Substitution based Text Attacks. Accepted by AAAI 2021.

Paper link: https://arxiv.org/abs/2008.03709
Code link: https://github.com/JHL-HUST/FGPM

Natural Language Adversarial Defense through Synonym Encoding. Accepted by UAI 2021.

Paper link: https://arxiv.org/abs/1909.06723
Code link: https://github.com/JHL-HUST/SEM

Thanks very much!

**Comment by Fanchao-Qi** [comment]
Thank you for your contributions. We have added the two papers.
