### ISSUE TITLE
Add a paper

### ISSUE THREAD

**Issue by skkuai** [thunlp/TAADpapers#25]
Hello, could you consider adding this paper?

Gradient-based Adversarial Attacks against Text Transformers. Facebook AI. 15 Apr 2021.

Paper link: https://arxiv.org/abs/2104.13733
Code link: https://github.com/facebookresearch/text-adversarial-attack

It is not published in the conference, but I think it is a great work.

Thanks very much!

**Comment by yangalan123** [comment]
Hi, thanks for the recommendations! However, as discussed in #9, we will not be able to list papers that have not been officially published yet except for the resource papers (e.g., dataset, benchmark) or the toolset papers which already have released their resource/toolset. However, we will keep a close look at this good paper and when it gets published we will be more than happy to add it to our list. 

If you have any further questions, please reply here. I am happy to discuss more.

**Comment by skkuai** [comment]
Thank you for explanation. I'm sorry I didn't check the previous issue. I couldn't agree more with you.
