### ISSUE TITLE
Corresponding Code Repo

### ISSUE THREAD

**Issue by Guyanqi** [thunlp/TAADpapers#3]
Thanks for your awesome collection.
Meanwhile, is it possible to add links to corresponding code repository (if exists) ?  That would be really helpful and convenient to look up. 
Thanks again!

**Comment by yangalan123** [comment]
Thanks for your advice! We will add links to available codes as soon as possible.

**Comment by yangalan123** [comment]
Code links have been added, except for some papers that we can not find the code links. Thanks for your advice again and please reopen the issue if you have any further problems.
