### ISSUE TITLE
add two papers

### ISSUE THREAD

**Issue by EdoardoMosca** [thunlp/TAADpapers#39]
[“That Is a Suspicious Reaction!”: Interpreting Logits Variation to Detect NLP Adversarial Attacks](https://aclanthology.org/2022.acl-long.538.pdf)
[Detecting Word-Level Adversarial Text Attacks via SHapley Additive exPlanations](https://aclanthology.org/2022.repl4nlp-1.16.pdf)

**Comment by yangalan123** [comment]
Hi @EdoardoMosca , thanks for your contribution! I have added your two papers in the `defense papers` section as I think detecting adversarial attacks is more relevant on the defense side. I have also attached your github repo link and pdf link for readers' reference. Let me know if you have further questions.
