### ISSUE TITLE
A couple of missing references

### ISSUE THREAD

**Issue by pminervini** [thunlp/TAADpapers#4]
- Adversarial attacks for Knowledge Base Completion models by finding inputs where the model violates background knowledge: https://arxiv.org/abs/1707.07596 (UAI 2017)
- A related approach for NLI models: https://arxiv.org/abs/1808.08609 (CoNLL 2018)

**Comment by yangalan123** [comment]
Thanks for your advice. We will check these papers and have a discussion.

**Comment by yangalan123** [comment]
Thank you for your contribution! We have decided to add your papers into the paper list. Please reopen the  issue if you have any further problem.
