### ISSUE TITLE
TextHoaxer: Budgeted Hard-Label Adversarial Attacks on Text

### ISSUE THREAD

**Issue by xunguangwang** [thunlp/TAADpapers#40]
Hi, my friends. I have seen one paper called "TextHoaxer: Budgeted Hard-Label Adversarial Attacks on Text", which is published on AAAI 2022. Why this paper is not included in the repository?

**Comment by yangalan123** [comment]
Hi, thanks for the recommendation. I may miss some papers as I am busy these days (I am the only remaining contributor now). It is excellent that you can recommend some new papers! Can you help initialize a PR, and I can take a look? Remember to change the number of paper at the top of README.

**Comment by xunguangwang** [comment]
Sure, wait for me for a while.

**Comment by xunguangwang** [comment]
Word-level Attack
38. TextHoaxer: Budgeted Hard-Label Adversarial Attacks on Text. Muchao Ye, Chenglin Miao, Ting Wang, Fenglong Ma. AAAI 2022. decision

**Comment by yangalan123** [comment]
Thanks for your contribution! I have added that entry. Next time, please submit a PR instead. In this way, we can easily recognize your contribution in Acknowledgement :-)
