### ISSUE TITLE
do you want to set up a new section for arxiv papers?

### ISSUE THREAD

**Issue by jind11** [thunlp/TAADpapers#9]
I know of several papers (almost close to 10) that have been put in arxiv but have not been accepted yet. Do you mind setting up a new section just for these arxiv papers?

**Comment by yangalan123** [comment]
Hi,
This is really an excellent question. Actually I have also seen several good papers only on Arxiv but have not been accepted. I am also thinking about quite the same thing as you advice -- should I open up a new section for them?  However, it is also true that not all such unpublished Arxiv papers are must-read ones. To keep this reading list more valuable and solid, adding such a paper generally requires a careful peer-review here, but I do not think we have the time, resource, and qualifications for that. So we decide to list papers officially accepted at some top-tier conferences or journals.

As a special exception, for resource paper, we sometimes recommend Arxiv papers after thorough investigation. For example, you may notice "Evaluating NLP Models via Contrast Sets" is also an unpublished Arxiv paper so far, but it is introduced by AI2 and the awesome author list (>10 NLP "big names") add much credence to this paper (these experts involved in the annotation work). Also, "Contrast Sets" is a resource paper and we find the resource accompanied by this paper has been officially released and well-documented. Therefore, the benefit of recommending this paper to the TAAD community outweighs the potential risk by far.

Still, I am excited that you bring about this good question and I am open to discuss this further. I have explained our consideration and exceptions. What do you think? If you have any advice, please comment on this issue.

**Comment by jind11** [comment]
Thanks for the detailed explanations! I agree with your opinion.
